#!/bin/sh

root=$PWD
cd edit_here
find . -type f | while read file
do
   mkdir -p ../generated/`dirname $file`
   mkdir -p ../`dirname $file`
   echo "<!-- DO NOT EDIT THIS FILE, EDIT THE ONES UNDER pages/ INSTEAD -->" > ../generated/$file
   cat $root/header.html $file ../footer.html |\
     sed -e 's/á/\&aacute;/g' \
         -e 's/é/\&eacute;/g' \
         -e 's/í/\&iacute;/g' \
         -e 's/ó/\&oacute;/g' \
         -e 's/ú/\&uacute;/g' \
         -e 's/à/\&agrave;/g' \
         -e 's/â/\&acirc;/g'  \
         -e 's/ê/\&ecirc;/g'  \
         -e 's/ô/\&ocirc;/g'  \
         -e 's/ã/\&atilde;/g' \
         -e 's/õ/\&otilde;/g' \
         -e 's/ç/\&ccedil;/g' \
     >> ../generated/$file
   ln -nfs $root/generated/$file ../$file
done
